### PR TITLE
accept numpy range

### PR DESCRIPTION
**Pull request by max-hoffman**

### CODE REVIEW

**Comment by pbronez** [comment]
@max-hoffman looks like this still fails on Python 3.9. Also, would be good to update the CI checks to include Python 3.10. That was [released in October 2021](https://www.python.org/downloads/)... Python 3.10.4 is current.

**Comment by pbronez** [comment]
> @max-hoffman looks like this still fails on Python 3.9.

Looking at the build logs, there was a problem with `typed_ast`. That [library is obsolete as of Python 3.8](https://pypi.org/project/typed-ast/) but [Black uses it for backwards compatibility](https://github.com/psf/black/blob/7f033136ac5e0e5bf6cf322dd60b4a92050eedc4/src/black/parsing.py#L155). The failed build used `black (20.8b1)`, latest version is `black (22.3.0)`. Maybe try loosening that constraint?  The [older version of black is pinned in doltpy's `pyproject.toml`](https://github.com/dolthub/doltpy/blob/d7c8596131e9f52aa2abc08f4b1c1526e0c22737/pyproject.toml#L32)

**Comment by max-hoffman** [comment]
Thank you for your interest @pbronez! Yes we can bump the black version. I have found that the downsides of a stale stable black is preferable to the codebase being subtly rewritten on unrelated PRs. In this case we'll bump.

The most recent active development of Doltpy was in 2020. We would encourage you to either use a sql-client interface, like [python-mysql-connector](https://dev.mysql.com/doc/connector-python/en/) or [doltcli](https://github.com/dolthub/doltcli), which does not have dependencies. The pandas/numpy integration removed in doltcli amounts to a csv -> pd.read_csv helper function. We try to support preexisting applications with a Doltpy dependence, but we are not currently investing in expanding into new Python version support.

Feel free to ask us more questions on our [Discord](https://discord.com/invite/RFwfYpu) if you would like.

**Comment by max-hoffman** [comment]
@pbronez After more investigation, we will not be able to test 3.9 and 3.10 in CI. If you find any functional deficiencies not satisfied by Doltpy our preferred interfaces, please let us know on Discord or file an issue and we will respond as soon as we see it. We do appreciate your interest and patience! But we are selling an application database. Shipping a database as fast as MySQL and covering every SQL interface gap is our all consuming focus.

**Comment by timsehn** [comment]
The additional problem here is that `doltpy` includes a ton of additional scope that we implemented before you could do almost everything through the SQL interface. We can't deprecate it because it may be in use but we only want to go so far at making it work with the latest and greatest Python.

**Pull request merged**
